apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2048
spec:
  selector:
    matchLabels:
      app: app-2048
  template:
    metadata:
      labels:
        app: app-2048
    spec:
      serviceAccountName: build-robot
      automountServiceAccountToken: false
      containers:
      - name: app-2048
        image: modernisation.azurecr.io/app2048:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

# sed -i 's/latest/$(Build.BuildId)/g' deployment.yml ;